// topics used in the input fields of the form that generates AI questions
export const topics = [
  "Angular",
  "Cloud Computing",
  "CSS",
  "DOM",
  "Express",
  "Git",
  "HTML",
  "JavaScript - Advanced",
  "JavaScript - Basics",
  "MongoDB",
  "Node",
  "Python",
  "React",
  "Testing",
  "SQL",
  "TypeScript",
  "Vue",
];
